# Generated by Django 4.0.5 on 2022-06-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='customer'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
